spring:
  datasource:
    url: jdbc:mysql://192.168.56.200:3306/traffic-lvs
    username: root
    password: Tv75aYT8@
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    redis:
      time-to-live: 600 # 一个以秒为单位的整数，表示缓存数据的生存时间
  data:
    redis:
      database: 0
      password:
      port: 6379
      lettuce:
        shutdown-timeout: 100ms
      host: 192.168.56.200

#指定接口包扫描
springdoc:
  api-docs:
    # 关闭 api-docs
    enabled: false
  swagger-ui:
    # 关闭 Swagger UI界面
    enabled: false
