spring:
  datasource:
    url: jdbc:mysql://192.168.56.200:3306/scaffold
    username: root
    password: Tv75aYT8@
    type: com.zaxxer.hikari.HikariDataSource
  data:
    elasticsearch:
      repositories:
        enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  elasticsearch:
    uris: http://192.168.56.200:9200


#指定接口包扫描
springdoc:
  packagesToScan: com.idiots.scaffold.controller
  # 配置需要生成接口文档的接口路径
#  paths-to-match: /api
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
elasticsearch:
  host: 192.168.56.200
  port: 9200
